name: Sphinx Build and Deploy

on: 
  push:
    branches: [docbuild]

jobs:
  pages:
    runs-on: ubuntu-latest
    #env:
    #  TZ: "Asia/Taipei"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: docbuild
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip install sphinx
      - name: Build
        run: |
          make -C docs html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./docs/build/html/
          publish_branch: gh-pages  # deploying branch
